# -*- coding: utf-8 -*-
"""farooq.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UrX-jgv4uvQOHmYr2fPKv6_D76O2Tqs6
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# %matplotlib inline
# %reload_ext autoreload
# %autoreload 2

"""# import data

"""

crash_df=sns.load_dataset('car_crashes')
crash_df

"""# Distribution plot"""

sns.distplot(crash_df['not_distracted'],kde=False, bins=25)

"""# Joint plot"""

sns.jointplot(x='speeding',y='alcohol',data=crash_df,kind='hex')

"""# KDE plot"""

sns.kdeplot(crash_df['alcohol'])

"""##pair plot"""

#

tips_df = sns.load_dataset('tips')

sns.pairplot(tips_df, hue='sex', palette='Blues')

"""##pair plot"""

#

tips_df = sns.load_dataset('tips')

sns.pairplot(tips_df, hue='sex', palette='Blues')

"""##RUG plot"""

sns.rugplot(tips_df['tip'])

"""##joint plot"""

sns.set_style('ticks')

plt.figure(figsize=(8,4))

sns.set_context('paper',font_scale=1.5)

sns.jointplot(x='speeding' , y='alcohol' , data=crash_df, kind='reg')

"""##bar plot"""

sns.barplot(x='sex',y='total_bill',data=tips_df ,estimator=np.cov)

"""##count plot"""

sns.countplot(x='sex',data=tips_df)

"""##box plot"""

sns.boxplot(x='day' , y='total_bill' , data=tips_df ,hue='sex')

plt.legend(loc=0)

"""##violin plot"""

sns.violinplot(x='day', y='total_bill', data=tips_df, hue='sex' ,split=True)

"""##strip plot"""

plt.figure(figsize=(8,5))

sns.stripplot(x='day',y='total_bill', data=tips_df ,jitter=True,hue='sex', dodge=True)

"""##swarm plot"""

sns.swarmplot(x='day', y='total_bill',data=tips_df)

plt.figure(figsize=(8,6))
sns.set_style('dark')
sns.set_context('talk')
sns.stripplot(x='day',y='total_bill',data=tips_df,hue='sex', palette='afmhot')

# upper right: 1, upper left: 2,lower left: 3, lower right:4,
plt.legend(loc=0)

"""##heatmap"""

plt.figure(figsize=(8,6))
sns.set_context('paper',font_scale=1.4)

crash_mx = crash_df.corr()

sns.heatmap(crash_mx, annot=True, cmap='Blues')

flights = sns.load_dataset('flights')
flights = flights.pivot_table(index='month',columns='year',values='passengers')
sns.heatmap(flights, cmap='Blues', linecolor='white',linewidth=1)

"""#cluster map"""

sns.clustermap(flights, cmap='Blues', standard_scale=1)

"""##pair grid"""

iris = sns.load_dataset('iris')
iris_g = sns.PairGrid(iris, hue='species')
iris_g.map_diag(plt.hist)
iris_g.map_offdiag(plt.scatter)
iris_g.map_upper(plt.scatter)
iris_g.map_lower(sns.kdeplot)
iris_g= sns.PairGrid(iris, hue='species',
                     x_vars=["sepal_length", "sepal_width"],
                     y_vars=["petal_length", "petal_width"])

"""##FacetGrid"""

att_df = sns.load_dataset('attention')
att_fg = sns.FacetGrid(att_df, col='subject', col_wrap=5, height=1.5)
att_fg.map(plt.plot, 'solutions', 'score', marker='.')

"""##regression plot"""

plt.figure(figsize=(8,6))
sns.set_context('paper',font_scale=1.4)
sns.lmplot(x='total_bill',y='tip' , hue='sex' , data=tips_df, markers=['o','^'],
           scatter_kws={'s':100, 'linewidth':0.5, 'edgecolor':'w'})

sns.set_context('paper', font_scale=1.4)
sns.lmplot(x='total_bill',y='tip', col='sex', row='time',data=tips_df,
           height=8, aspect=0.6)

